/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => YTranscriptPlugin
});
module.exports = __toCommonJS(main_exports);

// buffer-polyfill.js
if (typeof Buffer === "undefined") {
  globalThis.Buffer = {
    from: function(data) {
      if (data instanceof Uint8Array) {
        let binary = "";
        for (let i = 0; i < data.length; i++) {
          binary += String.fromCharCode(data[i]);
        }
        return {
          toString: function(encoding) {
            if (encoding === "base64") {
              return btoa(binary);
            }
            return binary;
          }
        };
      }
      return {
        toString: function(encoding) {
          if (encoding === "base64") {
            return btoa(String(data));
          }
          return String(data);
        }
      };
    }
  };
}

// src/main.ts
var import_obsidian4 = require("obsidian");

// src/transcript-view.ts
var import_obsidian2 = require("obsidian");

// src/youtube-transcript.ts
var import_obsidian = require("obsidian");

// src/types.ts
var YoutubeTranscriptError = class extends Error {
  constructor(err) {
    if (!(err instanceof Error)) {
      super("");
      return;
    }
    if (err.message.includes("ERR_INVALID_URL")) {
      super("無效的 YouTube 網址");
    } else {
      super(err.message);
    }
  }
};

// src/api-parser.ts
var YOUTUBE_TITLE_REGEX = new RegExp(
  /<meta\s+name="title"\s+content="([^"]*)\">/
);
var YOUTUBE_VIDEOID_REGEX = new RegExp(
  /<link\s+rel="canonical"\s+href="([^"]*)\">/
);
function decodeHtmlEntities(text) {
  return text.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'").replace(
    /&#(\d+);/g,
    (_, code) => String.fromCharCode(parseInt(code, 10))
  ).replace(
    /&#x([a-fA-F0-9]+);/g,
    (_, code) => String.fromCharCode(parseInt(code, 16))
  ).replace(/\n/g, " ").trim();
}
function parseTranscriptXml(xmlContent) {
  const lines = [];
  const textMatches = xmlContent.matchAll(
    /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g
  );
  for (const match of textMatches) {
    const startSeconds = parseFloat(match[1]);
    const durationSeconds = parseFloat(match[2]);
    const text = decodeHtmlEntities(match[3].replace(/<[^>]+>/g, ""));
    if (text) {
      lines.push({
        text,
        offset: Math.round(startSeconds * 1e3),
        duration: Math.round(durationSeconds * 1e3)
      });
    }
  }
  if (lines.length === 0) {
    const pMatches = xmlContent.matchAll(
      /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g
    );
    for (const match of pMatches) {
      const offset = parseInt(match[1], 10);
      const duration = parseInt(match[2], 10);
      const text = decodeHtmlEntities(match[3].replace(/<[^>]+>/g, ""));
      if (text) {
        lines.push({
          text,
          offset,
          duration
        });
      }
    }
  }
  if (lines.length === 0) {
    const timedTextMatches = xmlContent.matchAll(
      /<p\b([^>]*)>([\s\S]*?)<\/p>/g
    );
    for (const match of timedTextMatches) {
      const attrs = match[1];
      const rawText = match[2];
      const beginMatch = attrs.match(/\bbegin="([^"]+)"/);
      const endMatch = attrs.match(/\bend="([^"]+)"/);
      const durMatch = attrs.match(/\bdur="([^"]+)"/);
      const offset = parseTimeExpression(beginMatch == null ? void 0 : beginMatch[1]);
      const end = parseTimeExpression(endMatch == null ? void 0 : endMatch[1]);
      const duration = durMatch ? parseTimeExpression(durMatch[1]) : Math.max(0, end - offset);
      const text = decodeHtmlEntities(rawText.replace(/<br\s*\/?>/g, " ").replace(/<[^>]+>/g, " ")).replace(/\s+/g, " ").trim();
      if (text) {
        lines.push({
          text,
          offset,
          duration: Number.isFinite(duration) ? duration : 0
        });
      }
    }
  }
  return lines;
}
function parseTimeExpression(timeExpression) {
  if (!timeExpression || typeof timeExpression !== "string") {
    return 0;
  }
  const trimmed = timeExpression.trim();
  if (!trimmed) {
    return 0;
  }
  if (/^\d+$/.test(trimmed)) {
    return parseInt(trimmed, 10);
  }
  const secondsMatch = trimmed.match(/^([\d.]+)s$/);
  if (secondsMatch) {
    return Math.round(parseFloat(secondsMatch[1]) * 1e3);
  }
  const clockMatch = trimmed.match(/^(?:(\d+):)?(\d+):(\d+(?:\.\d+)?)$/);
  if (clockMatch) {
    const hours = parseInt(clockMatch[1] || "0", 10);
    const minutes = parseInt(clockMatch[2] || "0", 10);
    const seconds = parseFloat(clockMatch[3] || "0");
    return Math.round((hours * 3600 + minutes * 60 + seconds) * 1e3);
  }
  return 0;
}
function parseTranscriptJson(jsonContent) {
  let payload;
  try {
    payload = JSON.parse(jsonContent);
  } catch (error) {
    return [];
  }
  const events = Array.isArray(payload == null ? void 0 : payload.events) ? payload.events : [];
  const lines = [];
  for (const event of events) {
    const segments = Array.isArray(event == null ? void 0 : event.segs) ? event.segs : [];
    const text = segments.map((segment) => {
      var _a;
      return (_a = segment == null ? void 0 : segment.utf8) != null ? _a : "";
    }).join("").replace(/\n/g, " ").trim();
    if (!text) {
      continue;
    }
    const offset = typeof (event == null ? void 0 : event.tStartMs) === "number" ? event.tStartMs : 0;
    const duration = typeof (event == null ? void 0 : event.dDurationMs) === "number" ? event.dDurationMs : 0;
    lines.push({
      text: decodeHtmlEntities(text),
      offset,
      duration
    });
  }
  return lines;
}

// src/youtube-transcript.ts
var _YoutubeTranscript = class _YoutubeTranscript {
  static async getTranscript(url, config) {
    var _a, _b, _c, _d, _e, _f;
    try {
      const videoId = this.extractVideoIdFromUrl(url);
      if (!videoId) {
        throw new YoutubeTranscriptError(
          new Error(
            "無效的 YouTube 網址：無法擷取影片 ID"
          )
        );
      }
      console.log(`\u{1F3AC} Fetching transcript for video: ${videoId}`);
      const playerData = await this.fetchPlayerData(videoId, config);
      const title = ((_a = playerData.videoDetails) == null ? void 0 : _a.title) || "未知";
      const captionsData = (_b = playerData.captions) == null ? void 0 : _b.playerCaptionsTracklistRenderer;
      if (!captionsData || !captionsData.captionTracks) {
        throw new YoutubeTranscriptError(
          new Error("此影片沒有可用字幕")
        );
      }
      console.log(
        `\u{1F4DD} Found ${captionsData.captionTracks.length} caption track(s)`
      );
      const langCode = (config == null ? void 0 : config.lang) || "zh-TW";
      const captionTrack = this.findCaptionTrack(
        captionsData.captionTracks,
        langCode
      );
      if (!captionTrack) {
        const availableLangs = captionsData.captionTracks.map((t) => t.languageCode).join(", ");
        throw new YoutubeTranscriptError(
          new Error(
            `找不到語言 '${langCode}' 的逐字稿。可用語言：${availableLangs}`
          )
        );
      }
      const trackName = ((_e = (_d = (_c = captionTrack.name) == null ? void 0 : _c.runs) == null ? void 0 : _d[0]) == null ? void 0 : _e.text) || ((_f = captionTrack.name) == null ? void 0 : _f.simpleText) || captionTrack.languageCode;
      console.log(
        `\u{1F504} Using caption track: ${trackName} (${captionTrack.languageCode})`
      );
      const trackCode = captionTrack.languageCode.toLowerCase();
      const isTraditionalChineseTrack = ["zh-tw", "zh-hant", "zh-hk", "zh-mo"].includes(trackCode);
      const translationTarget = (config == null ? void 0 : config.autoTranslateToTraditionalChinese) && langCode.startsWith("zh") && !isTraditionalChineseTrack ? this.resolveTranslationTarget(captionsData, ["zh-TW", "zh-Hant", "zh-HK", "zh"]) : null;
      const transcriptUrl = translationTarget ? this.buildTranslatedTranscriptUrl(captionTrack.baseUrl, translationTarget) : captionTrack.baseUrl;
      if (translationTarget) {
        console.log(`\u{1F310} Auto-translating transcript to Traditional Chinese (${translationTarget})`);
      }
      console.log(
        `\u{1F4E5} Fetching transcript from: ${transcriptUrl.substring(0, 80)}...`
      );
      const lines = await this.fetchTranscriptWithFallback(
        transcriptUrl,
        captionTrack.baseUrl,
        !!translationTarget
      );
      console.log(
        `\u2705 Successfully fetched ${lines.length} transcript lines`
      );
      return {
        title: this.decodeHTML(title),
        lines
      };
    } catch (err) {
      const primaryError = err instanceof YoutubeTranscriptError ? err : new YoutubeTranscriptError(err);
      if (this.shouldUseYtDlpFallback(config)) {
        try {
          console.warn("\u26A0\uFE0F Primary transcript pipeline failed, trying yt-dlp fallback");
          return await this.getTranscriptWithYtDlp(url, config);
        } catch (fallbackError) {
          const fallbackMessage = fallbackError instanceof Error ? fallbackError.message : String(fallbackError);
          throw new YoutubeTranscriptError(
            new Error(`主流程失敗：${primaryError.message}；yt-dlp 備援失敗：${fallbackMessage}`)
          );
        }
      }
      throw primaryError;
    }
  }
  /**
   * Extract video ID from various YouTube URL formats
   */
  static extractVideoIdFromUrl(url) {
    const patterns = [
      /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/v\/)([a-zA-Z0-9_-]{11})/,
      /^([a-zA-Z0-9_-]{11})$/
      // Just the video ID
    ];
    for (const pattern of patterns) {
      const match = url.match(pattern);
      if (match) {
        return match[1];
      }
    }
    return null;
  }
  /**
   * Fetches player data from YouTube's InnerTube API using ANDROID client
   */
  static async fetchPlayerData(videoId, config) {
    const normalizedLang = this.normalizeLanguageCode(config == null ? void 0 : config.lang);
    const normalizedCountry = this.normalizeCountryCode(config == null ? void 0 : config.country);
    try {
      return await this.fetchPlayerDataWithContext(videoId, normalizedLang, normalizedCountry);
    } catch (error) {
      try {
        if (normalizedLang !== "en" || normalizedCountry !== "US") {
          console.warn("\u26A0\uFE0F Player API request failed with configured locale, retrying with en/US");
          return await this.fetchPlayerDataWithContext(videoId, "en", "US");
        }
      } catch (fallbackError) {
        console.warn("\u26A0\uFE0F Player API request failed with en/US, falling back to watch page parsing");
      }
      return await this.fetchPlayerDataFromWatchPage(videoId, normalizedLang);
    }
  }
  static async fetchPlayerDataWithContext(videoId, langCode, countryCode) {
    const context = {
      ..._YoutubeTranscript.INNERTUBE_CONTEXT,
      client: {
        ..._YoutubeTranscript.INNERTUBE_CONTEXT.client,
        hl: langCode,
        gl: countryCode
      }
    };
    const requestBody = {
      context,
      videoId
    };
    console.log(`\u{1F504} Calling InnerTube Player API with ANDROID client...`);
    const response = await (0, import_obsidian.requestUrl)({
      url: _YoutubeTranscript.INNERTUBE_PLAYER_URL,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": "com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip"
      },
      body: JSON.stringify(requestBody)
    });
    const data = JSON.parse(response.text);
    const playabilityStatus = data.playabilityStatus;
    if (playabilityStatus) {
      console.log(`\u{1F4CA} Playability status: ${playabilityStatus.status}`);
      if (playabilityStatus.status === "ERROR") {
        throw new Error(
          playabilityStatus.reason || "Video unavailable"
        );
      }
      if (playabilityStatus.status === "LOGIN_REQUIRED") {
        throw new Error("此影片需登入後才能觀看");
      }
      if (playabilityStatus.status === "UNPLAYABLE") {
        throw new Error(
          playabilityStatus.reason || "Video is unplayable"
        );
      }
    }
    return data;
  }
  static async fetchPlayerDataFromWatchPage(videoId, langCode) {
    const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=${encodeURIComponent(langCode)}`;
    console.log(`\u{1F310} Falling back to watch page parsing: ${watchUrl}`);
    const response = await (0, import_obsidian.requestUrl)({
      url: watchUrl,
      method: "GET",
      headers: {
        "Accept-Language": "zh-TW,zh-Hant;q=0.9,zh;q=0.8,en;q=0.6",
        "User-Agent": "Mozilla/5.0"
      }
    });
    const playerData = this.extractPlayerDataFromHtml(response.text);
    const playabilityStatus = playerData.playabilityStatus;
    if (playabilityStatus) {
      if (playabilityStatus.status === "ERROR") {
        throw new Error(
          playabilityStatus.reason || "Video unavailable"
        );
      }
      if (playabilityStatus.status === "LOGIN_REQUIRED") {
        throw new Error("此影片需登入後才能觀看");
      }
      if (playabilityStatus.status === "UNPLAYABLE") {
        throw new Error(
          playabilityStatus.reason || "Video is unplayable"
        );
      }
    }
    return playerData;
  }
  /**
   * Finds the best matching caption track for the requested language
   */
  static findCaptionTrack(captionTracks, langCode) {
    let track = captionTracks.find((t) => t.languageCode === langCode);
    if (track) return track;
    if (langCode.startsWith("zh")) {
      const zhPreferredCodes = ["zh-TW", "zh-Hant", "zh-HK", "zh"];
      for (const code of zhPreferredCodes) {
        track = captionTracks.find((t) => t.languageCode === code);
        if (track) return track;
      }
      track = captionTracks.find((t) => t.languageCode.startsWith("zh-"));
      if (track) return track;
    }
    track = captionTracks.find(
      (t) => t.languageCode.startsWith(langCode + "-")
    );
    if (track) return track;
    track = captionTracks.find(
      (t) => langCode.startsWith(t.languageCode + "-")
    );
    if (track) return track;
    if (captionTracks.length > 0) {
      console.log(
        `\u26A0\uFE0F 找不到語言 '${langCode}'，改用 '${captionTracks[0].languageCode}'`
      );
      return captionTracks[0];
    }
    return null;
  }
  /**
   * Fetches transcript XML from the caption track URL
   */
  static async fetchTranscriptFromUrl(transcriptUrl) {
    const response = await (0, import_obsidian.requestUrl)({
      url: transcriptUrl,
      method: "GET",
      headers: {
        "Accept-Language": "zh-TW,zh-Hant;q=0.9,zh;q=0.8,en;q=0.6"
      }
    });
    console.log(
      `\u{1F4C4} Transcript response length: ${response.text.length} bytes`
    );
    if (response.text.length > 0) {
      const parsedLines = this.parseTranscriptResponse(response.text);
      if (parsedLines.length > 0) {
        return parsedLines;
      }
    }
    const jsonUrl = this.buildTranscriptFormatUrl(transcriptUrl, "json3");
    if (jsonUrl !== transcriptUrl) {
      console.warn("\u26A0\uFE0F Transcript response was empty or unparsable, retrying with fmt=json3");
      const jsonResponse = await (0, import_obsidian.requestUrl)({
        url: jsonUrl,
        method: "GET",
        headers: {
          "Accept-Language": "zh-TW,zh-Hant;q=0.9,zh;q=0.8,en;q=0.6"
        }
      });
      console.log(
        `\u{1F4C4} Transcript json3 response length: ${jsonResponse.text.length} bytes`
      );
      const parsedJsonLines = this.parseTranscriptResponse(jsonResponse.text);
      if (parsedJsonLines.length > 0) {
        return parsedJsonLines;
      }
    }
    throw new Error("收到空白逐字稿回應");
  }
  static async fetchTranscriptWithFallback(transcriptUrl, fallbackUrl, canFallbackToOriginal) {
    try {
      return await this.fetchTranscriptFromUrl(transcriptUrl);
    } catch (error) {
      if (!canFallbackToOriginal || transcriptUrl === fallbackUrl) {
        throw error;
      }
      console.warn("\u26A0\uFE0F Translated transcript request failed, retrying with original caption track");
      return await this.fetchTranscriptFromUrl(fallbackUrl);
    }
  }
  static buildTranslatedTranscriptUrl(transcriptUrl, targetLang) {
    try {
      const urlObj = new URL(transcriptUrl);
      urlObj.searchParams.set("tlang", targetLang);
      return urlObj.toString();
    } catch (error) {
      const divider = transcriptUrl.includes("?") ? "&" : "?";
      return `${transcriptUrl}${divider}tlang=${encodeURIComponent(targetLang)}`;
    }
  }
  static buildTranscriptFormatUrl(transcriptUrl, format) {
    try {
      const urlObj = new URL(transcriptUrl);
      urlObj.searchParams.set("fmt", format);
      return urlObj.toString();
    } catch (error) {
      const divider = transcriptUrl.includes("?") ? "&" : "?";
      return `${transcriptUrl}${divider}fmt=${encodeURIComponent(format)}`;
    }
  }
  static parseTranscriptResponse(responseText) {
    const trimmed = responseText.trim();
    if (!trimmed) {
      return [];
    }
    if (trimmed.startsWith("{")) {
      return parseTranscriptJson(trimmed);
    }
    return parseTranscriptXml(trimmed);
  }
  static resolveTranslationTarget(captionsData, preferredCodes) {
    var _a;
    const translationLanguages = (_a = captionsData == null ? void 0 : captionsData.translationLanguages) != null ? _a : [];
    if (!Array.isArray(translationLanguages) || translationLanguages.length === 0) {
      return null;
    }
    const availableCodes = translationLanguages.map((lang) => lang.languageCode).filter((code) => typeof code === "string");
    for (const code of preferredCodes) {
      if (availableCodes.includes(code)) {
        return code;
      }
    }
    const zhCode = availableCodes.find((code) => code.startsWith("zh"));
    return zhCode != null ? zhCode : null;
  }
  static normalizeLanguageCode(langCode) {
    if (typeof langCode !== "string") {
      return "zh-TW";
    }
    const normalized = langCode.trim();
    if (!normalized) {
      return "zh-TW";
    }
    return normalized;
  }
  static normalizeCountryCode(countryCode) {
    if (typeof countryCode !== "string") {
      return "TW";
    }
    const normalized = countryCode.trim().toUpperCase();
    if (/^[A-Z]{2}$/.test(normalized)) {
      return normalized;
    }
    return "TW";
  }
  static extractPlayerDataFromHtml(html) {
    const marker = "ytInitialPlayerResponse = ";
    const data = this.extractJsonAfterMarker(html, marker);
    if (data) {
      return JSON.parse(data);
    }
    const fallbackMarker = '"playerResponse":';
    const fallbackData = this.extractJsonAfterMarker(html, fallbackMarker);
    if (fallbackData) {
      return JSON.parse(fallbackData);
    }
    throw new Error("無法從影片頁面擷取播放器資料");
  }
  static extractJsonAfterMarker(text, marker) {
    const markerIndex = text.indexOf(marker);
    if (markerIndex === -1) {
      return null;
    }
    const jsonStart = text.indexOf("{", markerIndex + marker.length);
    if (jsonStart === -1) {
      return null;
    }
    let depth = 0;
    let inString = false;
    let isEscaped = false;
    for (let i = jsonStart; i < text.length; i++) {
      const char = text[i];
      if (inString) {
        if (isEscaped) {
          isEscaped = false;
        } else if (char === "\\") {
          isEscaped = true;
        } else if (char === '"') {
          inString = false;
        }
        continue;
      }
      if (char === '"') {
        inString = true;
        continue;
      }
      if (char === "{") {
        depth++;
      } else if (char === "}") {
        depth--;
        if (depth === 0) {
          return text.slice(jsonStart, i + 1);
        }
      }
    }
    return null;
  }
  static shouldUseYtDlpFallback(config) {
    return (config == null ? void 0 : config.enableYtDlpFallback) !== false;
  }
  static isDesktopRuntime() {
    return !!(import_obsidian.Platform && import_obsidian.Platform.isDesktopApp);
  }
  static getNodeModulesForYtDlp() {
    try {
      return {
        childProcess: require("child_process"),
        fs: require("fs"),
        os: require("os"),
        path: require("path")
      };
    } catch (error) {
      throw new Error("目前環境無法使用 yt-dlp（缺少 Node.js 執行能力）");
    }
  }
  static resolveYtDlpExecutableCandidates(config) {
    const fs = require("fs");
    const candidates = [];
    const customPath = (config == null ? void 0 : config.ytDlpPath) ? String(config.ytDlpPath).trim() : "";
    if (customPath) {
      candidates.push(customPath);
    }
    const bundledPath = this.getBundledYtDlpPath();
    if (!candidates.includes(bundledPath) && fs.existsSync(bundledPath)) {
      candidates.push(bundledPath);
    }
    if (!candidates.includes("yt-dlp")) {
      candidates.push("yt-dlp");
    }
    if (import_obsidian.Platform && import_obsidian.Platform.isWin && !candidates.includes("yt-dlp.exe")) {
      candidates.push("yt-dlp.exe");
    }
    return candidates;
  }
  static getBundledYtDlpPath() {
    const path = require("path");
    const exeName = import_obsidian.Platform && import_obsidian.Platform.isWin ? "yt-dlp.exe" : "yt-dlp";
    return path.join(__dirname, exeName);
  }
  static getYtDlpWorkingRoot(config) {
    const fs = require("fs");
    const path = require("path");
    const candidates = this.resolveYtDlpExecutableCandidates(config);
    for (const candidate of candidates) {
      if (!path.isAbsolute(candidate) || !fs.existsSync(candidate)) {
        continue;
      }
      const candidateDir = path.dirname(candidate);
      try {
        if (fs.statSync(candidateDir).isDirectory()) {
          return candidateDir;
        }
      } catch (error) {
      }
    }
    const bundledDir = path.dirname(this.getBundledYtDlpPath());
    try {
      if (fs.statSync(bundledDir).isDirectory()) {
        return bundledDir;
      }
    } catch (error) {
    }
    return process.cwd();
  }
  static async spawnProcess(command, args, options) {
    return await new Promise((resolve, reject) => {
      const child = options.childProcess.spawn(command, args, {
        cwd: options.cwd,
        windowsHide: true,
        env: options.env
      });
      let stdout = "";
      let stderr = "";
      child.stdout.on("data", (chunk) => {
        stdout += chunk.toString();
      });
      child.stderr.on("data", (chunk) => {
        stderr += chunk.toString();
      });
      child.on("error", (error) => {
        reject(error);
      });
      child.on("close", (code) => {
        if (code === 0 || options.allowNonZeroExit) {
          resolve({ stdout, stderr });
        } else {
          reject(new Error(`exit code ${code}; ${stderr || stdout || "無輸出"}`));
        }
      });
    });
  }
  static detectLanguageCodeFromFilename(filename) {
    const parts = filename.split(".");
    for (let i = parts.length - 2; i >= 0; i--) {
      const part = parts[i];
      if (/^[a-z]{2,3}(?:-[a-z0-9]+)*$/i.test(part) && part.toLowerCase() !== "subtitle") {
        return part.toLowerCase();
      }
    }
    return "";
  }
  static getSubtitleLanguageRank(languageCode) {
    if (!languageCode) return 100;
    if (languageCode === "zh-tw" || languageCode === "zh-hant") return 0;
    if (languageCode === "zh-hk" || languageCode === "zh-mo") return 1;
    if (languageCode.startsWith("zh")) return 2;
    if (languageCode.startsWith("en")) return 3;
    if (languageCode.startsWith("ja")) return 4;
    return 50;
  }
  static pickBestSubtitleFile(files) {
    const sorted = [...files].sort((a, b) => {
      const langRankA = this.getSubtitleLanguageRank(this.detectLanguageCodeFromFilename(a));
      const langRankB = this.getSubtitleLanguageRank(this.detectLanguageCodeFromFilename(b));
      if (langRankA !== langRankB) {
        return langRankA - langRankB;
      }
      const extRankA = a.toLowerCase().endsWith(".vtt") ? 0 : 1;
      const extRankB = b.toLowerCase().endsWith(".vtt") ? 0 : 1;
      return extRankA - extRankB;
    });
    return sorted[0];
  }
  static parseSubtitleTimestamp(timestamp) {
    const normalized = timestamp.trim().replace(",", ".");
    const match = normalized.match(/^(?:(\d+):)?(\d{1,2}):(\d{2})(?:\.(\d{1,3}))?$/);
    if (!match) {
      return 0;
    }
    const hours = parseInt(match[1] || "0", 10);
    const minutes = parseInt(match[2] || "0", 10);
    const seconds = parseInt(match[3] || "0", 10);
    const millis = parseInt((match[4] || "0").padEnd(3, "0"), 10);
    return (hours * 3600 + minutes * 60 + seconds) * 1e3 + millis;
  }
  static parseVttContent(content) {
    const blocks = content.replace(/\r/g, "").split(/\n{2,}/);
    const lines = [];
    for (const block of blocks) {
      const rows = block.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);
      if (rows.length === 0 || rows[0].startsWith("WEBVTT") || rows[0].startsWith("NOTE")) {
        continue;
      }
      const timeLineIndex = rows.findIndex((row) => row.includes("-->"));
      if (timeLineIndex === -1) {
        continue;
      }
      const timingParts = rows[timeLineIndex].split("-->");
      if (timingParts.length < 2) {
        continue;
      }
      const start = this.parseSubtitleTimestamp(timingParts[0].trim().split(" ")[0]);
      const end = this.parseSubtitleTimestamp(timingParts[1].trim().split(" ")[0]);
      const text = rows.slice(timeLineIndex + 1).join(" ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
      if (!text) {
        continue;
      }
      lines.push({
        text: decodeHtmlEntities(text),
        offset: start,
        duration: Math.max(0, end - start)
      });
    }
    return lines;
  }
  static parseSrtContent(content) {
    const blocks = content.replace(/\r/g, "").split(/\n{2,}/);
    const lines = [];
    for (const block of blocks) {
      const rows = block.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);
      if (rows.length < 2) {
        continue;
      }
      const timeLineIndex = rows.findIndex((row) => row.includes("-->"));
      if (timeLineIndex === -1) {
        continue;
      }
      const timingParts = rows[timeLineIndex].split("-->");
      if (timingParts.length < 2) {
        continue;
      }
      const start = this.parseSubtitleTimestamp(timingParts[0].trim());
      const end = this.parseSubtitleTimestamp(timingParts[1].trim());
      const text = rows.slice(timeLineIndex + 1).join(" ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
      if (!text) {
        continue;
      }
      lines.push({
        text: decodeHtmlEntities(text),
        offset: start,
        duration: Math.max(0, end - start)
      });
    }
    return lines;
  }
  static parseSubtitleContent(content, filename) {
    if (filename.toLowerCase().endsWith(".srt")) {
      return this.parseSrtContent(content);
    }
    return this.parseVttContent(content);
  }
  static async getTranscriptWithYtDlp(url, config) {
    if (!this.isDesktopRuntime()) {
      throw new Error("yt-dlp 備援僅支援桌面版 Obsidian");
    }
    const modules = this.getNodeModulesForYtDlp();
    let tempDir = "";
    try {
      const ytDlpCandidates = this.resolveYtDlpExecutableCandidates(config);
      const ytDlpWorkingRoot = this.getYtDlpWorkingRoot(config);
      tempDir = modules.path.join(
        ytDlpWorkingRoot,
        ".yt-dlp-tmp",
        `ytranscript-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
      );
      modules.fs.mkdirSync(tempDir, { recursive: true });
      const outputTemplate = modules.path.join(tempDir, "subtitle.%(ext)s");
      const processEnv = {
        ...process.env,
        TEMP: tempDir,
        TMP: tempDir,
        TMPDIR: tempDir,
        PYINSTALLER_RESET_ENVIRONMENT: "1"
      };
      const args = [
        "--skip-download",
        "--ignore-errors",
        "--no-abort-on-error",
        "--no-warnings",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs",
        "zh-TW,zh-Hant,zh-HK,zh.*,en.*,ja.*",
        "--sub-format",
        "vtt/srt",
        "--output",
        outputTemplate,
        url
      ];
      let lastError = null;
      let usedExecutable = "";
      for (const candidate of ytDlpCandidates) {
        try {
          console.log(`\u{1F6E0}\uFE0F Running yt-dlp fallback with executable: ${candidate}`);
          const result = await this.spawnProcess(candidate, args, {
            cwd: tempDir,
            childProcess: modules.childProcess,
            env: processEnv,
            allowNonZeroExit: true
          });
          if (result.stderr && result.stderr.trim()) {
            console.warn(`\u26A0\uFE0F yt-dlp stderr (${candidate}): ${result.stderr.trim()}`);
          }
          usedExecutable = candidate;
          break;
        } catch (error) {
          lastError = error;
          const reason = error instanceof Error ? error.message : String(error);
          console.warn(`\u26A0\uFE0F yt-dlp executable failed: ${candidate}; ${reason}`);
        }
      }
      if (!usedExecutable) {
        const reason = lastError instanceof Error ? lastError.message : String(lastError);
        throw new Error(`無法執行 yt-dlp，候選路徑皆失敗：${ytDlpCandidates.join(", ")}；${reason}`);
      }
      const subtitleFiles = modules.fs.readdirSync(tempDir).filter((file) => /\.(vtt|srt)$/i.test(file));
      if (subtitleFiles.length === 0) {
        throw new Error("yt-dlp 未輸出任何字幕檔，請確認系統已安裝 yt-dlp");
      }
      const bestSubtitleFile = this.pickBestSubtitleFile(subtitleFiles);
      const subtitlePath = modules.path.join(tempDir, bestSubtitleFile);
      const subtitleContent = modules.fs.readFileSync(subtitlePath, "utf8");
      const lines = this.parseSubtitleContent(subtitleContent, bestSubtitleFile);
      if (lines.length === 0) {
        throw new Error(`yt-dlp 字幕檔解析後為空：${bestSubtitleFile}`);
      }
      const detectedLang = this.detectLanguageCodeFromFilename(bestSubtitleFile);
      if (detectedLang && !detectedLang.startsWith("zh")) {
        console.warn(`\u26A0\uFE0F yt-dlp fallback could not find Traditional Chinese subtitles; using '${detectedLang}'`);
      }
      return {
        title: "YouTube 逐字稿",
        lines
      };
    } finally {
      if (tempDir) {
        try {
          modules.fs.rmSync(tempDir, { recursive: true, force: true });
        } catch (cleanupError) {
        }
      }
    }
  }
  /**
   * Decodes HTML entities in a text string
   */
  static decodeHTML(text) {
    return text.replace(/&#39;/g, "'").replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(
      /&#(\d+);/g,
      (_, code) => String.fromCharCode(parseInt(code, 10))
    ).replace(/\\n/g, " ").replace(/\s+/g, " ").trim();
  }
};
// YouTube's public InnerTube API key
_YoutubeTranscript.INNERTUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";
_YoutubeTranscript.INNERTUBE_PLAYER_URL = `https://www.youtube.com/youtubei/v1/player?key=${_YoutubeTranscript.INNERTUBE_API_KEY}`;
// Use ANDROID client like youtube-transcript-api does - it's less restricted
_YoutubeTranscript.INNERTUBE_CONTEXT = {
  client: {
    clientName: "ANDROID",
    clientVersion: "19.09.37",
    androidSdkVersion: 30,
    hl: "en",
    gl: "US"
  }
};
var YoutubeTranscript = _YoutubeTranscript;

// src/timestampt-utils.ts
var formatTimestamp = (t) => {
  if (t < 0) return "00:00";
  const fnum = (n) => `${n | 0}`.padStart(2, "0");
  const s = 1e3;
  const m = 60 * s;
  const h = 60 * m;
  const hours = Math.floor(t / h);
  const minutes = Math.floor((t - hours * h) / m);
  const seconds = Math.floor((t - hours * h - minutes * m) / s);
  const time = hours ? [hours, minutes, seconds] : [minutes, seconds];
  return time.map(fnum).join(":");
};

// src/render-utils.ts
var highlightText = (div, searchValue) => {
  const content = div.innerHTML;
  const highlightedContent = content.replace(
    new RegExp(searchValue, "gi"),
    '<span class="yt-transcript__highlight">$&</span>'
  );
  div.innerHTML = highlightedContent;
};
var getTranscriptBlocks = (data, timestampMod) => {
  const transcriptBlocks = [];
  let quote = "";
  let quoteTimeOffset = 0;
  data.forEach((line, i) => {
    if (i === 0) {
      quoteTimeOffset = line.offset;
      quote += line.text + " ";
      return;
    }
    if (i % timestampMod == 0) {
      transcriptBlocks.push({
        quote,
        quoteTimeOffset
      });
      quote = "";
      quoteTimeOffset = line.offset;
    }
    quote += line.text + " ";
  });
  if (quote !== "") {
    transcriptBlocks.push({
      quote,
      quoteTimeOffset
    });
  }
  return transcriptBlocks;
};

// src/transcript-view.ts
var TRANSCRIPT_TYPE_VIEW = "transcript-view";
var TranscriptView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.videoData = [];
    this.plugin = plugin;
    this.isDataLoaded = false;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h4", { text: "逐字稿" });
  }
  async onClose() {
    const leafIndex = this.getLeafIndex();
    this.plugin.settings.leafUrls.splice(leafIndex, 1);
  }
  /**
   * Gets the leaf index out of all of the open leaves
   * This assumes that the leaf order shouldn't changed, which is a fair assumption
   */
  getLeafIndex() {
    const leaves = this.app.workspace.getLeavesOfType(TRANSCRIPT_TYPE_VIEW);
    return leaves.findIndex((leaf) => leaf === this.leaf);
  }
  /**
   * Adds a div with loading text to the view content
   */
  renderLoader() {
    if (this.loaderContainerEl !== void 0) {
      this.loaderContainerEl.createEl("div", {
        text: "載入中..."
      });
    }
  }
  /**
   * Adds a text input to the view content
   */
  renderSearchInput(url, data, timestampMod) {
    const searchInputEl = this.contentEl.createEl("input");
    searchInputEl.type = "text";
    searchInputEl.placeholder = "搜尋...";
    searchInputEl.style.marginBottom = "20px";
    searchInputEl.addEventListener("input", (e) => {
      const searchFilter = e.target.value;
      this.renderTranscriptionBlocks(
        url,
        data,
        timestampMod,
        searchFilter
      );
    });
  }
  /**
   * Renders a button that imports transcript into current markdown note
   */
  renderImportButton(url, data, timestampMod) {
    const importButtonEl = this.contentEl.createEl("button", {
      text: "匯入到目前筆記"
    });
    importButtonEl.addClass("mod-cta");
    importButtonEl.style.marginBottom = "12px";
    importButtonEl.addEventListener("click", () => {
      const transcriptBlocks = getTranscriptBlocks(
        data.lines,
        timestampMod
      );
      this.insertBlocksToCurrentNote(url, transcriptBlocks);
    });
  }
  /**
   * Gets markdown editor from active view or fallback markdown leaves
   */
  getTargetMarkdownEditor() {
    const activeMarkdownView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (activeMarkdownView == null ? void 0 : activeMarkdownView.editor) {
      return activeMarkdownView.editor;
    }
    const markdownLeaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of markdownLeaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian2.MarkdownView && view.editor) {
        return view.editor;
      }
    }
    return null;
  }
  /**
   * Inserts transcript blocks into the current markdown note
   */
  insertBlocksToCurrentNote(url, blocks) {
    if (!blocks || blocks.length === 0) {
      new import_obsidian2.Notice("沒有可匯入的逐字稿內容");
      return;
    }
    const editor = this.getTargetMarkdownEditor();
    if (!editor) {
      new import_obsidian2.Notice("請先開啟一個 Markdown 筆記");
      return;
    }
    const content = this.formatPlainContentToPaste(blocks);
    if (!content || content.trim().length === 0) {
      new import_obsidian2.Notice("沒有可匯入的逐字稿內容");
      return;
    }
    const cursor = editor.getCursor();
    const wrappedContent = [
      "---",
      "",
      "## 逐字稿",
      "```",
      content,
      "```",
      "---"
    ].join("\n");
    const insertContent = (cursor.ch > 0 ? "\n" : "") + wrappedContent + "\n";
    editor.replaceRange(insertContent, cursor);
    new import_obsidian2.Notice(`已匯入 ${blocks.length} 段逐字稿`);
  }
  /**
   * Adds a div with the video title to the view content
   * @param title - the title of the video
   */
  renderVideoTitle(title) {
    const titleEl = this.contentEl.createEl("div");
    titleEl.innerHTML = title;
    titleEl.style.fontWeight = "bold";
    titleEl.style.marginBottom = "20px";
  }
  formatContentToPaste(url, blocks) {
    return blocks.map((block) => {
      const { quote, quoteTimeOffset } = block;
      const href = url + "&t=" + Math.floor(quoteTimeOffset / 1e3);
      const formattedBlock = `[${formatTimestamp(
        quoteTimeOffset
      )}](${href}) ${quote}`;
      return formattedBlock;
    }).join("\n");
  }
  formatPlainContentToPaste(blocks) {
    return blocks.map((block) => block.quote.trim()).filter((quote) => quote.length > 0).join("\n");
  }
  /**
   * Add a transcription blocks to the view content
   * @param url - the url of the video
   * @param data - the transcript data
   * @param timestampMod - the number of seconds between each timestamp
   * @param searchValue - the value to search for in the transcript
   */
  renderTranscriptionBlocks(url, data, timestampMod, searchValue) {
    const dataContainerEl = this.dataContainerEl;
    if (dataContainerEl !== void 0) {
      dataContainerEl.empty();
      const transcriptBlocks = getTranscriptBlocks(
        data.lines,
        timestampMod
      );
      const filteredBlocks = transcriptBlocks.filter(
        (block) => block.quote.toLowerCase().includes(searchValue.toLowerCase())
      );
      filteredBlocks.forEach((block) => {
        const { quote, quoteTimeOffset } = block;
        const blockContainerEl = createEl("div", {
          cls: "yt-transcript__transcript-block"
        });
        blockContainerEl.draggable = true;
        const linkEl = createEl("a", {
          text: formatTimestamp(quoteTimeOffset),
          attr: {
            href: url + "&t=" + Math.floor(quoteTimeOffset / 1e3)
          }
        });
        linkEl.style.marginBottom = "5px";
        const span = dataContainerEl.createEl("span", {
          text: quote,
          title: "點擊即可複製"
        });
        span.addEventListener("click", (event) => {
          var _a;
          const target = event.target;
          if (target !== null) {
            navigator.clipboard.writeText((_a = target.textContent) != null ? _a : "");
          }
        });
        if (searchValue !== "") highlightText(span, searchValue);
        blockContainerEl.appendChild(linkEl);
        blockContainerEl.appendChild(span);
        blockContainerEl.addEventListener(
          "dragstart",
          (event) => {
            var _a;
            (_a = event.dataTransfer) == null ? void 0 : _a.setData(
              "text/html",
              blockContainerEl.innerHTML
            );
          }
        );
        blockContainerEl.addEventListener(
          "contextmenu",
          (event) => {
            const menu = new import_obsidian2.Menu();
            menu.addItem(
              (item) => item.setTitle("全部複製").onClick(() => {
                navigator.clipboard.writeText(
                  this.formatContentToPaste(
                    url,
                    filteredBlocks
                  )
                );
              })
            );
            menu.addItem(
              (item) => item.setTitle("匯入到目前筆記").onClick(() => {
                this.insertBlocksToCurrentNote(url, filteredBlocks);
              })
            );
            menu.showAtPosition({
              x: event.clientX,
              y: event.clientY
            });
          }
        );
        dataContainerEl.appendChild(blockContainerEl);
      });
    }
  }
  /**
   * Sets the state of the view
   * This is called when the view is loaded
   */
  async setEphemeralState(state) {
    var _a;
    if (this.isDataLoaded) return;
    const leafIndex = this.getLeafIndex();
    if (state.url) {
      this.plugin.settings.leafUrls[leafIndex] = state.url;
      await this.plugin.saveSettings();
    }
    const { lang, country, timestampMod, leafUrls, autoTranslateToTraditionalChinese, enableYtDlpFallback, ytDlpPath } = this.plugin.settings;
    const url = leafUrls[leafIndex];
    try {
      if (this.loaderContainerEl === void 0) {
        this.loaderContainerEl = this.contentEl.createEl("div");
      } else {
        this.loaderContainerEl.empty();
      }
      this.renderLoader();
      const data = await YoutubeTranscript.getTranscript(url, {
        lang,
        country,
        autoTranslateToTraditionalChinese,
        enableYtDlpFallback,
        ytDlpPath
      });
      if (!data) throw Error();
      this.isDataLoaded = true;
      this.loaderContainerEl.empty();
      this.renderVideoTitle(data.title);
      this.renderImportButton(url, data, timestampMod);
      this.renderSearchInput(url, data, timestampMod);
      if (this.dataContainerEl === void 0) {
        this.dataContainerEl = this.contentEl.createEl("div");
      } else {
        this.dataContainerEl.empty();
      }
      if (this.errorContainerEl !== void 0) {
        this.errorContainerEl.empty();
      }
      if (data.lines.length === 0) {
        this.dataContainerEl.createEl("h4", {
          text: "找不到逐字稿"
        });
        this.dataContainerEl.createEl("div", {
          text: "請確認影片是否有字幕，或在外掛設定調整語言與國家代碼。"
        });
      } else {
        this.renderTranscriptionBlocks(url, data, timestampMod, "");
      }
    } catch (err) {
      let errorMessage = "";
      if (err instanceof YoutubeTranscriptError) {
        errorMessage = err.message;
      }
      (_a = this.loaderContainerEl) == null ? void 0 : _a.empty();
      if (this.errorContainerEl === void 0) {
        this.errorContainerEl = this.contentEl.createEl("h5");
      } else {
        this.errorContainerEl.empty();
      }
      const titleEl = this.errorContainerEl.createEl("div", {
        text: "載入逐字稿時發生錯誤"
      });
      titleEl.style.marginBottom = "5px";
      const messageEl = this.errorContainerEl.createEl("div", {
        text: errorMessage
      });
      messageEl.style.color = "var(--text-muted)";
      messageEl.style.fontSize = "var(--font-ui-small)";
    }
  }
  getViewType() {
    return TRANSCRIPT_TYPE_VIEW;
  }
  getDisplayText() {
    return "YouTube 逐字稿";
  }
  getIcon() {
    return "scroll";
  }
};

// src/prompt-modal.ts
var import_obsidian3 = require("obsidian");
var PromptModal = class extends import_obsidian3.Modal {
  constructor(initialValue) {
    super(app);
    this.submitted = false;
    this.initialValue = initialValue;
    this.value = initialValue || "";
  }
  listenInput(evt) {
    if (evt.key === "Enter") {
      evt.preventDefault();
      this.enterCallback(evt);
    }
  }
  onOpen() {
    this.titleEl.setText("YouTube 網址");
    this.createForm();
  }
  onClose() {
    this.contentEl.empty();
    if (!this.submitted) {
      this.reject();
    }
  }
  createForm() {
    const textInput = new import_obsidian3.TextComponent(this.contentEl);
    textInput.inputEl.style.width = "100%";
    textInput.onChange((value) => this.value = value);
    textInput.inputEl.addEventListener(
      "keydown",
      (evt) => this.enterCallback(evt)
    );
    if (this.initialValue) {
      textInput.setValue(this.initialValue);
      textInput.inputEl.select();
    }
    textInput.inputEl.focus();
    const buttonDiv = this.modalEl.createDiv();
    buttonDiv.addClass("modal-button-container");
    const submitButton = new import_obsidian3.ButtonComponent(buttonDiv);
    submitButton.buttonEl.addClass("mod-cta");
    submitButton.setButtonText("確認").onClick((evt) => {
      this.resolveAndClose(evt);
    });
  }
  enterCallback(evt) {
    if (evt.key === "Enter") {
      this.resolveAndClose(evt);
    }
  }
  resolveAndClose(evt) {
    this.submitted = true;
    evt.preventDefault();
    this.resolve(this.value);
    this.close();
  }
  async openAndGetValue(resolve, reject) {
    this.resolve = resolve;
    this.reject = reject;
    this.open();
  }
};

// src/url-utils.ts
var UrlPattern = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
function _getLinkNearestCursor(textLine, cursorPosition, linksInLine) {
  if (cursorPosition > textLine.length)
    throw new Error("游標超出該行範圍");
  if (!linksInLine || linksInLine.length < 1)
    throw new Error("找不到連結");
  for (let i = 0; i < linksInLine.length; i++) {
    const link = linksInLine[i];
    const index = linksInLine.length > i + 1 ? textLine.indexOf(linksInLine[i + 1]) : textLine.length;
    if (cursorPosition <= index) return link;
  }
  throw new Error("未預期的錯誤");
}
function getUrlFromText(lineText, cursorPosition) {
  var _a;
  const url = _getLinkNearestCursor(
    lineText,
    cursorPosition,
    (_a = lineText.match(UrlPattern)) != null ? _a : []
  );
  return [lineText.indexOf(url), lineText.indexOf(url) + url.length];
}

// editor-extensions.ts
var EditorExtensions = class {
  static getSelectedText(editor) {
    if (!editor.somethingSelected()) {
      const wordBoundaries = this.getWordBoundaries(editor);
      editor.setSelection(wordBoundaries[0], wordBoundaries[1]);
    }
    return editor.getSelection();
  }
  static getWordBoundaries(editor) {
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    const urlPosition = getUrlFromText(lineText, cursor.ch);
    return [
      { line: cursor.line, ch: urlPosition[0] },
      { line: cursor.line, ch: urlPosition[1] }
    ];
  }
};

// src/url-detection.ts
var URLDetector = class {
  /**
   * Checks if the provided URL is a valid YouTube URL
   * @param url - The URL to validate
   * @returns true if the URL is a valid YouTube URL, false otherwise
   */
  static isValidYouTubeUrl(url) {
    if (!url || typeof url !== "string") {
      return false;
    }
    try {
      const urlObj = new URL(url);
      const hostname = urlObj.hostname.toLowerCase();
      const isYouTubeDomain = this.YOUTUBE_DOMAINS.includes(hostname);
      if (!isYouTubeDomain) {
        return false;
      }
      if (hostname.includes("youtube.com")) {
        return urlObj.pathname === "/watch" && urlObj.searchParams.has("v");
      }
      if (hostname.includes("youtu.be")) {
        const pathParts = urlObj.pathname.split("/");
        return pathParts.length >= 2 && pathParts[1].length > 0;
      }
      return false;
    } catch (error) {
      return false;
    }
  }
  /**
   * Extracts the first valid YouTube URL found in the provided text
   * @param text - The text to search for YouTube URLs
   * @returns The first valid YouTube URL found, or null if none found
   */
  static extractYouTubeUrlFromText(text) {
    if (!text || typeof text !== "string") {
      return null;
    }
    const urlRegex = /https?:\/\/[^\s<>"{}|\\^`[\]]+/gi;
    const matches = text.match(urlRegex);
    if (!matches) {
      return null;
    }
    for (const match of matches) {
      if (this.isValidYouTubeUrl(match)) {
        return match;
      }
    }
    return null;
  }
  /**
   * Creates a YouTube URL with a timestamp parameter
   * @param url - The base YouTube URL
   * @param offsetMs - The timestamp offset in milliseconds
   * @returns The URL with timestamp parameter added
   */
  static buildTimestampUrl(url, offsetMs) {
    if (!url || typeof url !== "string") {
      return "";
    }
    try {
      const urlObj = new URL(url);
      const seconds = Math.max(0, Math.floor(offsetMs / 1e3));
      urlObj.searchParams.set("t", seconds.toString());
      return urlObj.toString();
    } catch (error) {
      return url;
    }
  }
};
// YouTube URL patterns to match various formats
URLDetector.YOUTUBE_URL_PATTERNS = [
  /https?:\/\/(?:www\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi,
  /https?:\/\/(?:www\.)?youtu\.be\/[\w-]+(?:[?][\w=&-]*)?/gi,
  /https?:\/\/(?:m\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi,
  /https?:\/\/(?:mobile\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi,
  /https?:\/\/(?:music\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi
];
// More comprehensive regex for matching YouTube URLs
URLDetector.YOUTUBE_DOMAINS = [
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "mobile.youtube.com",
  "music.youtube.com",
  "youtu.be",
  "www.youtu.be"
];

// src/transcript-formatter.ts
var TranscriptFormatter = class {
  /**
   * Formats a transcript response according to the specified template and options
   * @param transcript - The transcript response to format
   * @param url - The source YouTube URL
   * @param options - Formatting options including template and timestamp frequency
   * @returns The formatted transcript string
   */
  static format(transcript, url, options) {
    if (!transcript || !transcript.lines || !Array.isArray(transcript.lines)) {
      return "";
    }
    if (transcript.lines.length === 0) {
      return "";
    }
    const normalizedOptions = this.normalizeOptions(options);
    const template = normalizedOptions.template || "standard" /* STANDARD */;
    switch (template) {
      case "minimal" /* MINIMAL */:
        return this.formatMinimalTemplate(
          transcript,
          url,
          normalizedOptions
        );
      case "standard" /* STANDARD */:
        return this.formatStandardTemplate(
          transcript,
          url,
          normalizedOptions
        );
      case "rich" /* RICH */:
        return this.formatRichTemplate(
          transcript,
          url,
          normalizedOptions
        );
      default:
        return this.formatStandardTemplate(
          transcript,
          url,
          normalizedOptions
        );
    }
  }
  /**
   * Convenience method to format transcript with minimal template
   */
  static formatMinimal(transcript, url, options) {
    return this.format(transcript, url, {
      ...options,
      template: "minimal" /* MINIMAL */
    });
  }
  /**
   * Convenience method to format transcript with standard template
   */
  static formatStandard(transcript, url, options) {
    return this.format(transcript, url, {
      ...options,
      template: "standard" /* STANDARD */
    });
  }
  /**
   * Convenience method to format transcript with rich template
   */
  static formatRich(transcript, url, options) {
    return this.format(transcript, url, {
      ...options,
      template: "rich" /* RICH */
    });
  }
  /**
   * Normalizes and validates formatting options
   */
  static normalizeOptions(options) {
    const normalized = {
      timestampMod: Math.max(1, Math.floor(options.timestampMod)) || 5,
      template: options.template || "standard" /* STANDARD */
    };
    if (options.timestampMod <= 0) {
      normalized.timestampMod = 1;
    }
    return normalized;
  }
  /**
   * Formats transcript as plain text without timestamps
   */
  static formatMinimalTemplate(transcript, url, options) {
    return transcript.lines.map((line) => line.text.trim()).filter((text) => text.length > 0).join(" ");
  }
  /**
   * Formats transcript with clickable timestamps
   */
  static formatStandardTemplate(transcript, url, options) {
    const blocks = getTranscriptBlocks(
      transcript.lines,
      options.timestampMod
    );
    if (blocks.length === 0) {
      return "";
    }
    return blocks.map((block) => {
      const { quote, quoteTimeOffset } = block;
      const timestampStr = formatTimestamp(quoteTimeOffset);
      const timestampUrl = url ? URLDetector.buildTimestampUrl(url, quoteTimeOffset) : "#";
      return `[${timestampStr}](${timestampUrl}) ${quote.trim()}`;
    }).join("\n");
  }
  /**
   * Formats transcript with metadata header and clickable timestamps
   */
  static formatRichTemplate(transcript, url, options) {
    const title = transcript.title && transcript.title.trim() ? transcript.title.trim() : "YouTube 逐字稿";
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const sourceUrl = url || "未知";
    const header = [
      `## ${title}`,
      `**來源**: ${sourceUrl}`,
      `**擷取日期**: ${today}`,
      ""
      // Empty line before transcript
    ].join("\n");
    const standardContent = this.formatStandardTemplate(
      transcript,
      url,
      options
    );
    return header + standardContent;
  }
};

// src/commands/insert-transcript.ts
var InsertTranscriptCommand = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  /**
   * Executes the insert transcript command with default settings
   */
  async execute(editor) {
    await this.executeWithOptions(editor, {});
  }
  /**
   * Executes the insert transcript command with custom options
   */
  async executeWithOptions(editor, options) {
    try {
      const url = await this.getYouTubeUrlWithConfirmation(editor);
      if (!url) {
        return;
      }
      if (!URLDetector.isValidYouTubeUrl(url)) {
        return;
      }
      const transcriptConfig = this.createTranscriptConfig();
      const transcript = await YoutubeTranscript.getTranscript(
        url,
        transcriptConfig
      );
      if (!transcript || !transcript.lines || transcript.lines.length === 0) {
        return;
      }
      const formatOptions = this.mergeFormatOptions(options);
      const formattedContent = TranscriptFormatter.format(
        transcript,
        url,
        formatOptions
      );
      if (!formattedContent || formattedContent.trim().length === 0) {
        return;
      }
      const cursor = editor.getCursor();
      editor.replaceRange(formattedContent, cursor);
    } catch (error) {
      console.error("Insert transcript failed:", error);
    }
  }
  /**
   * Gets YouTube URL with user confirmation via prompt
   * Always shows prompt, but pre-populates with detected URL
   */
  async getYouTubeUrlWithConfirmation(editor) {
    const detectedUrl = await this.detectYouTubeUrl(editor);
    try {
      const prompt = new PromptModal(detectedUrl || void 0);
      const userUrl = await new Promise((resolve, reject) => {
        prompt.openAndGetValue(resolve, reject);
      });
      return userUrl.trim() || null;
    } catch (error) {
      return null;
    }
  }
  /**
   * Detects YouTube URL from selection or clipboard (for pre-populating prompt)
   */
  async detectYouTubeUrl(editor) {
    const selectionUrl = this.getUrlFromSelection(editor);
    if (selectionUrl) {
      return selectionUrl;
    }
    const clipboardUrl = await this.getUrlFromClipboard();
    if (clipboardUrl) {
      return clipboardUrl;
    }
    return null;
  }
  /**
   * Gets URL from current editor selection
   */
  getUrlFromSelection(editor) {
    try {
      const selectedText = editor.somethingSelected() ? editor.getSelection() : EditorExtensions.getSelectedText(editor);
      return URLDetector.extractYouTubeUrlFromText(selectedText);
    } catch (error) {
      return null;
    }
  }
  /**
   * Gets URL from system clipboard
   */
  async getUrlFromClipboard() {
    try {
      const clipboardText = await navigator.clipboard.readText();
      return URLDetector.extractYouTubeUrlFromText(clipboardText);
    } catch (error) {
      return null;
    }
  }
  /**
   * Creates transcript config from plugin settings
   */
  createTranscriptConfig() {
    var _a, _b, _c, _d, _e;
    return {
      lang: (_a = this.plugin.settings) == null ? void 0 : _a.lang,
      country: (_b = this.plugin.settings) == null ? void 0 : _b.country,
      autoTranslateToTraditionalChinese: (_c = this.plugin.settings) == null ? void 0 : _c.autoTranslateToTraditionalChinese,
      enableYtDlpFallback: (_d = this.plugin.settings) == null ? void 0 : _d.enableYtDlpFallback,
      ytDlpPath: (_e = this.plugin.settings) == null ? void 0 : _e.ytDlpPath
    };
  }
  /**
   * Merges user options with plugin settings
   */
  mergeFormatOptions(options) {
    var _a;
    return {
      template: options.template || "minimal" /* MINIMAL */,
      timestampMod: options.timestampMod || ((_a = this.plugin.settings) == null ? void 0 : _a.timestampMod) || 5
    };
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  timestampMod: 5,
  lang: "zh-TW",
  country: "TW",
  autoTranslateToTraditionalChinese: true,
  enableYtDlpFallback: true,
  ytDlpPath: YoutubeTranscript.getBundledYtDlpPath(),
  leafUrls: []
};
var YTranscriptPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.insertTranscriptCommand = new InsertTranscriptCommand(this);
    this.registerView(
      TRANSCRIPT_TYPE_VIEW,
      (leaf) => new TranscriptView(leaf, this)
    );
    this.addCommand({
      id: "transcript-from-text",
      name: "從選取網址取得 YouTube 逐字稿",
      editorCallback: (editor, _) => {
        const url = EditorExtensions.getSelectedText(editor).trim();
        this.openView(url);
      }
    });
    this.addCommand({
      id: "transcript-from-prompt",
      name: "透過輸入網址取得 YouTube 逐字稿",
      callback: async () => {
        const prompt = new PromptModal();
        const url = await new Promise(
          (resolve) => prompt.openAndGetValue(resolve, () => {
          })
        );
        if (url) {
          this.openView(url);
        }
      }
    });
    this.addCommand({
      id: "insert-youtube-transcript",
      name: "插入 YouTube 逐字稿",
      editorCallback: async (editor, _) => {
        await this.insertTranscriptCommand.execute(editor);
      }
    });
    this.addSettingTab(new YTranslateSettingTab(this.app, this));
  }
  async openView(url) {
    const leaf = this.app.workspace.getRightLeaf(false);
    await leaf.setViewState({
      type: TRANSCRIPT_TYPE_VIEW
    });
    this.app.workspace.revealLeaf(leaf);
    leaf.setEphemeralState({
      url
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(TRANSCRIPT_TYPE_VIEW);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    this.settings.lang = YoutubeTranscript.normalizeLanguageCode(this.settings.lang === "en" ? "zh-TW" : this.settings.lang);
    this.settings.country = YoutubeTranscript.normalizeCountryCode(this.settings.country === "EN" ? "TW" : this.settings.country);
    if (typeof this.settings.autoTranslateToTraditionalChinese !== "boolean") {
      this.settings.autoTranslateToTraditionalChinese = true;
    }
    if (typeof this.settings.enableYtDlpFallback !== "boolean") {
      this.settings.enableYtDlpFallback = true;
    }
    if (typeof this.settings.ytDlpPath !== "string") {
      this.settings.ytDlpPath = "";
    }
    if (!this.settings.ytDlpPath.trim()) {
      this.settings.ytDlpPath = YoutubeTranscript.getBundledYtDlpPath();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var YTranslateSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "YTranscript 設定" });
    new import_obsidian4.Setting(containerEl).setName("時間戳記間隔").setDesc(
      "決定文字中時間戳記出現頻率（1 = 每行，10 = 每 10 行）"
    ).addText(
      (text) => text.setValue(this.plugin.settings.timestampMod.toFixed()).onChange(async (value) => {
        const v = Number.parseInt(value);
        this.plugin.settings.timestampMod = Number.isNaN(v) ? 5 : v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("語言").setDesc("偏好的逐字稿語言").addText(
      (text) => text.setValue(this.plugin.settings.lang).onChange(async (value) => {
        this.plugin.settings.lang = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("國家").setDesc("偏好的逐字稿國家代碼").addText(
      (text) => text.setValue(this.plugin.settings.country).onChange(async (value) => {
        this.plugin.settings.country = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("自動翻譯為繁體中文").setDesc("當影片沒有繁體中文字幕時，自動使用 YouTube 字幕翻譯").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoTranslateToTraditionalChinese !== false).onChange(async (value) => {
        this.plugin.settings.autoTranslateToTraditionalChinese = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("啟用 yt-dlp 備援").setDesc("當一般流程抓不到字幕時，改用本機 yt-dlp 嘗試擷取（僅桌面版）").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableYtDlpFallback !== false).onChange(async (value) => {
        this.plugin.settings.enableYtDlpFallback = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("yt-dlp 執行檔路徑").setDesc("留空會使用外掛目錄內的 yt-dlp；也可填入完整路徑").addText(
      (text) => text.setPlaceholder(YoutubeTranscript.getBundledYtDlpPath()).setValue(this.plugin.settings.ytDlpPath || "").onChange(async (value) => {
        this.plugin.settings.ytDlpPath = value.trim() || YoutubeTranscript.getBundledYtDlpPath();
        await this.plugin.saveSettings();
      })
    );
  }
};

/* nosourcemap */
